{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled (not .Values.ingress.tls.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octo.ingress.tlsSecretName" . }}
  labels:
    {{- include "octo.labels" . | nindent 4 }}
type: Opaque
stringData:
  qcloud_cert_id: {{ required "ingress.tls.certId must be set when ingress TLS is enabled" .Values.ingress.tls.certId | quote }}
{{- end }}
